### ISSUE TITLE
Multiple instance

### ISSUE THREAD

**Issue by toreba** [alexcode/vue2vis#14]
Hi

I'm trying to add multiple instance of network on the same page. This almost works, but calling methods via $refs.networkA.... gets mixed up. 

As far as I can see, the reason is the module variable "network" inside Network.vue. It will point to the last instance created.

**Comment by alexcode** [comment]
@Menighin, any idea on this ?

**Comment by Menighin** [comment]
Hi @alexcode and @toreba,

I've been really busy last few weeks. This is on my "to-do" list. Will try to have a look this week.

**Comment by ohjeohje** [comment]
Same problem with timeline.

**Comment by Menighin** [comment]
@alexcode I think if we change it back as a ""hidden property"" as it was [here](https://github.com/alexcode/vue2vis/blob/9ec148095db962dc4b318d6b22f89e468d358c1e/src/components/Network.vue#L285) it may work. Maybe is the same solution for timeline. Will do some testing today. Do you remember having any downsides with this approach?

**Comment by alexcode** [comment]
I guess this is fixed by the PR.

**Comment by Menighin** [comment]
We still need to fix for the other components though.
Will do it today (Y)

**Comment by vakrolme** [comment]
I think the problem might be still present with at least the 'format' property/function as demonstrated here: https://jsfiddle.net/mb8ypnvz/

I have two timelines and I want them to have different label formatting. When I set `options.format` on timeline_2, it affects timeline_1 as well.

Any way to fix it?
